from pathlib import Path

import typer
from pydantic import ValidationError

from src.aosp import (
    archive_url,
    clang_key,
    download_tarball,
    fetch_metadata,
    fetch_tree_from_branches,
    find_clang_revs,
)
from src.error import GitilesError, TelegramError
from src.github import create_github_release, github_repo_url, tag_exists
from src.logger import LOGGER as logger
from src.logger import configure_logging
from src.models import ClangMetadata
from src.telegram import send_message

DEFAULT_METADATA_FILE = Path("metadata.json")
TOOLCHAIN_DIR = Path("toolchain")

app = typer.Typer(
    name="aosp-clang-mirror",
    help="Fetch latest AOSP Clang and mirror to GitHub Releases",
    no_args_is_help=True,
    rich_markup_mode="rich",
    pretty_exceptions_enable=True,
    pretty_exceptions_show_locals=False,
)


def load_metadata(path: Path) -> ClangMetadata:
    try:
        return ClangMetadata.model_validate_json(path.read_text(encoding="utf-8"))
    except (OSError, ValidationError) as error:
        logger.error("Failed to read metadata from %s: %s", path, error)
        raise typer.Exit(1) from error


def save_metadata(path: Path, metadata: ClangMetadata) -> None:
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(metadata.model_dump_json(indent=2) + "\n", encoding="utf-8")
    except OSError as error:
        logger.error("Failed to write metadata to %s: %s", path, error)
        raise typer.Exit(1) from error


def release_asset(revision: str) -> Path:
    return TOOLCHAIN_DIR / f"{revision}.tar.gz"


@app.command()
def fetch(
    metadata_file: Path = typer.Option(
        DEFAULT_METADATA_FILE,
        "--metadata",
        help="Path where the JSON metadata file should be saved",
    ),
) -> None:
    try:
        branch, tree = fetch_tree_from_branches()
        latest_clang = max(find_clang_revs(tree), key=clang_key)
    except GitilesError:
        logger.exception("Failed to fetch AOSP Clang tree")
        raise typer.Exit(1)

    logger.info("Found latest revision %s from branch %s", latest_clang, branch)

    try:
        build_id, clang_version = fetch_metadata(branch, latest_clang)
    except (GitilesError, ValidationError) as error:
        logger.error("Failed to fetch Clang metadata: %s", error)
        raise typer.Exit(1) from error

    new_tag = f"{latest_clang}-{build_id}"
    logger.info("Target release tag: %s", new_tag)

    try:
        exists = tag_exists(new_tag)
        if not exists:
            download_tarball(
                archive_url(branch, latest_clang),
                release_asset(latest_clang),
            )
    except OSError, RuntimeError:
        logger.exception("Failed to prepare Clang release")
        raise typer.Exit(1)

    if exists:
        logger.info("%s is already released. Skipping download.", new_tag)

    metadata = ClangMetadata(
        latest_clang=latest_clang,
        build_id=build_id,
        clang_version=clang_version,
        new_tag=new_tag,
        exists=exists,
        branch=branch,
    )
    save_metadata(metadata_file, metadata)
    logger.info("Wrote metadata to %s.", metadata_file)


@app.command()
def release(
    metadata_file: Path = typer.Option(
        DEFAULT_METADATA_FILE,
        "--metadata",
        help="Path to the JSON metadata file generated by fetch",
    ),
) -> None:
    metadata = load_metadata(metadata_file)

    if metadata.exists:
        logger.info(
            "Release tag %s already exists. Skipping release creation.",
            metadata.new_tag,
        )
        return

    asset = release_asset(metadata.latest_clang)
    if not asset.is_file():
        logger.error("Release asset not found: %s", asset)
        raise typer.Exit(1)

    try:
        create_github_release(metadata.new_tag, asset)
    except RuntimeError:
        logger.exception("Failed to create GitHub release")
        raise typer.Exit(1)


@app.command()
def notify(
    metadata_file: Path = typer.Option(
        DEFAULT_METADATA_FILE,
        "--metadata",
        help="Path to the JSON metadata file generated by fetch",
    ),
) -> None:
    metadata = load_metadata(metadata_file)

    if metadata.exists:
        logger.info("Latest Clang is already released. Skipping notification.")
        return

    alt_version = metadata.latest_clang.removeprefix("clang-")
    github_tarball = (
        f"{github_repo_url()}/releases/download/{metadata.new_tag}/{metadata.latest_clang}.tar.gz"
    )
    archive_tarball = archive_url(metadata.branch, metadata.latest_clang)

    message_lines = [
        "*Google Clang Prebuilt Update*",
        "",
        f"*Clang Version*: {metadata.clang_version} ({alt_version})",
        f"*Build ID*: {metadata.build_id}",
        "",
        "*Download tar.gz*:",
        f"[Download (GitHub mirror)]({github_tarball})",
        f"[Download (AOSP source)]({archive_tarball})",
    ]

    logger.info("Sending Telegram notification...")
    try:
        send_message("\n".join(message_lines))
    except TelegramError:
        logger.exception("Failed to send Telegram notification")
        raise typer.Exit(1)
    logger.info("Notification sent successfully.")


if __name__ == "__main__":
    configure_logging()
    app()
