name: Cleanup Workflows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *' 
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update && sudo apt install -qq git jq gh

      - name: Clean up workflows run
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run list \
            --status completed \
            --limit 1000 \
            --json databaseId \
            -q '.[].databaseId' \
          | xargs -n1 gh run delete
